apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
spec:
  selector:
    matchLabels:
      app: yolo-client-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo-client-deployment
    spec:
      containers:
        - name: yolo-client-deployment
          image: magdamag/yolo-client:v1.1.0
          ports:
            - containerPort: 3000