apiVersion: v1
kind: Service
metadata:
  name: yolo-client-deployment
  labels:
    run: yolo-client-deployment
spec:
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: yolo-client-deployment
  type: LoadBalancer